#.travis.yml

sudo: required
dist: trusty

language: node_js
node_js:
  - 6.9

branches:
  only:
    - master
    - develop
    - /^greenkeeper.*$/

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm run build

notifications:
  email:
    on_failure: always

before_deploy:
  - mv dist/static/CNAME dist/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: dist
