#.travis.yml

sudo: required
dist: trusty

language: node_js
node_js:
  - 6.9

branches:
  only:
    - master
    - develop
    - /^greenkeeper.*$/

cache:
  yarn: true
  directories:
    - node_modules

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - . ci/travis/before_install.sh

install:
  - . ci/travis/install.sh

script:
  - . ci/travis/script.sh

notifications:
  email:
    on_failure: always

before_deploy:
  - . ci/travis/before_deploy.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  fqdn: nummering.nl
  email: maartenpaauw@gmail.com
  name: "Maarten Paauw"
  on:
    branch: master
